### ISSUE TITLE
Potential issue: Attempting to update with the exact object retrieved from canvas

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/canvas-api-wrapper#18]
It might cause issues if we try to update an item using the same object retrieved from canvas. We might have permissions to GET something, but not update it, so it would throw a 403. Some things, like IDs, aren't something we can update.

**Comment by benjameep** [comment]
I noticed canvas doing the same thing on their website (sending all of the data to an update instead of just what was being updated) so I assume that their server is built to handle this. If it does mess things up, then I have added an optional parameter on update which you can specify the body of the post to use instead of the object
